server.port=8080

azure.activedirectory.tenant-id=5625266d-cae0-4070-a7ea-b5e88273580f
azure.activedirectory.client-id=20ae8f6f-ef82-48a6-a4ae-897d36212b4b

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${azure.activedirectory.tenant-id}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://${azure.activedirectory.client-id}
