server.port=8080

# Configuracion de Azure AD JWT (Reemplazar TU_TENANT_ID por tu Id de inquilino de Azure)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/TU_TENANT_ID/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://TU_CLIENT_ID
