server.port=8080

azure.activedirectory.tenant-id=5625266d-cae0-4070-a7ea-b5e88273580f
azure.activedirectory.client-id=9a946a0b-5350-4fe1-a79e-ca332612f60d

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${azure.activedirectory.tenant-id}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://${azure.activedirectory.client-id}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG


reciclago.services.catalog-url=http://localhost:8081
reciclago.services.pickups-url=http://localhost:8083
reciclago.services.routes-url=http://localhost:8084